@url = http://localhost:8000/api/v1
@token = Bearer ownId

@scrapId = id


POST  {{url}}/scraps HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
	"scrap": {
		"title":"hoge2",
		"body":"hoge"
	}
}

###


GET {{url}}/scraps/{{scrapId}} HTTP/1.1
content-type: application/json
Authorization: {{token}}


###


PUT {{url}}/scraps/{{scrapId}} HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
	"property": {
		"isPublic":true
	}
}

###


DELETE  {{url}}/scraps/{{scrapId}} HTTP/1.1
content-type: application/json
Authorization: {{token}}
