@url = http://localhost:8000/api/v1
@token = Bearer ownId


GET {{url}}/users/me HTTP/1.1
content-type: application/json
Authorization: {{token}}

###

PUT {{url}}/users/me HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
	"name": "waimatuhoge"
}

###

PUT {{url}}/users/me/isExecutedTutorial HTTP/1.1
content-type: application/json
Authorization: {{token}}

###

@userId = userId

GET {{url}}/users/{{userId}} HTTP/1.1
content-type: application/json
Authorization: {{token}}