@url = http://localhost:8000/api/v1
@token = Bearer 9224100ec7aa73f009328ea5925c572964bcc003ccd020c5140a92a4dae48dfe


GET  {{url}}/users/me HTTP/1.1
content-type: application/json
Authorization: {{token}}

###

PUT   {{url}}/users/me HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
	"name": "waimatu"
}

###

PUT   {{url}}/users/me/isExecutedTutorial HTTP/1.1
content-type: application/json
Authorization: {{token}}
